trigger:
  - main

pool:
  name: 'Default'

variables:
  node_version: '20.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Instalar Node.js'

- script: |
    npm install
  displayName: 'Instalar dependencias'

- script: |
    npm run build --if-present
  displayName: 'Compilar proyecto'

- script: |
    npm run dev --if-present
  displayName: 'Dev proyecto'

# Paso opcional: Empaquetar archivos para el despliegue
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'