trigger:
  - main

pool:
  name: 'Default'

variables:
  node_version: '20.x'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)
  displayName: 'Instalar Node.js'

- script: |
    npm install
  displayName: 'Instalar dependencias'

- script: |
    npm run build --if-present
  displayName: 'Compilar proyecto (Build)'
  env:
    # A veces el build necesita variables (ej. Next.js)
    PORT: $(PORT)
    DATABASE_URL: $(DATABASE_URL)
    DB_PASSWORD: $(DB_PASSWORD)
    CORS_ORIGIN: $(CORS_ORIGIN)

# Opcional: Ejecutar tests antes de empaquetar
- script: |
    npm test --if-present
  displayName: 'Ejecutar Pruebas'

- task: ArchiveFiles@2
  displayName: 'Comprimir artefactos'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publicar el ZIP (Drop)'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'